### ISSUE TITLE
Commission rate is not getting updated 

### ISSUE THREAD

**Issue by aditya-manit** [stationmoney/station#134]
I have edited my commission rate to 10% yesterday it has been 25 hours now but the station link still shows 20%

I just broadcasted the same tx again but it's still the same.

Tx where I edited commission rate: https://finder.terra.money/mainnet/tx/3a690991672df1f79176649140536314399d2da00d4f64d6b9d052de8816a1b5

Validator Profile Still says 20%: https://station.terra.money/validator/terravaloper1yh4u76y405t3ff9lyrzhhe8legjx9k3as5mujs

Here is the onchain data

```
commission:
  commission_rates:
    max_change_rate: "0.200000000000000000"
    max_rate: "0.200000000000000000"
    rate: "0.100000000000000000"
  update_time: "2022-11-29T05:45:56.374072354Z"
consensus_pubkey:
  '@type': /cosmos.crypto.ed25519.PubKey
  key: 8BjjEMyaJKBgoVhCp7IHyVqLKNIugZFUhEfE40k5Eig=
delegator_shares: "4124205150535.000000000000000000"
description:
  details: Stake with the King
  identity: C8992BB62C009B9F
  moniker: KingSuper
  security_contact: ""
  website: https://king.super.site
jailed: false
min_self_delegation: "1"
operator_address: terravaloper1yh4u76y405t3ff9lyrzhhe8legjx9k3as5mujs
status: BOND_STATUS_BONDED
tokens: "4124205150535"
unbonding_height: "0"
unbonding_time: "1970-01-01T00:00:00Z"
```
